Feature: Project

  Scenario: Create a new project
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto"
    And I click on the Login button new project with selector "body > div.wrapper > div > main > div > div > div.mb-3.d-flex.justify-content-between.align-items-center > a"
    And I enter in the project name field with name "nombre" the text "NewProjectWithPhase"
    And I enter in the client field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(1) > span > span.selection > span"
    And I enter in the client-value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(1) > select > option:nth-child(2)"
    And I enter in the project manager field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(2) > span > span.selection > span"
    And I enter in the project manager value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(2) > select > option:nth-child(2)"
    And I enter in the project type field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > span > span.selection > span"
    And I enter in the project type value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)"
    And I enter in the date field with selector "#daterange"
    And I enter in the startdate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(1) > td:nth-child(7)"
    And I enter in the enddate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(6) > td:nth-child(2)"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/create"

  Scenario: Create a new project with initial phase
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto"
    And I click on the Login button new project with selector "body > div.wrapper > div > main > div > div > div.mb-3.d-flex.justify-content-between.align-items-center > a"
    And I enter in the project name field with name "nombre" the text "NewProjectWithPhase"
    And I enter in the client field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(1) > span > span.selection > span"
    And I enter in the client-value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(1) > select > option:nth-child(2)"
    And I enter in the project manager field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(2) > span > span.selection > span"
    And I enter in the project manager value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(2) > select > option:nth-child(2)"
    And I enter in the project type field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > span > span.selection > span"
    And I enter in the project type value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)"
    And I enter in the date field with selector "#daterange"
    And I enter in the startdate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(1) > td:nth-child(7)"
    And I enter in the enddate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(6) > td:nth-child(2)"
    And I click on new phase "#agregarNuevaFase"
    And I enter in the phase name field with id "#fase1 > div.row.mt-4 > div:nth-child(1) > div > input" the text "Phase 1"
    And I enter in the phase hour field with id "#fase1 > div.row.mt-4 > div:nth-child(2) > div > input" the text "22"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/create"

  Scenario: Create a new project with more than one initial phase
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto"
    And I click on the Login button new project with selector "body > div.wrapper > div > main > div > div > div.mb-3.d-flex.justify-content-between.align-items-center > a"
    And I enter in the project name field with name "nombre" the text "NewProjectWith2Phases"
    And I enter in the client field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(1) > span > span.selection > span"
    And I enter in the client-value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(1) > select > option:nth-child(2)"
    And I enter in the project manager field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(2) > span > span.selection > span"
    And I enter in the project manager value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(3) > div:nth-child(2) > select > option:nth-child(2)"
    And I enter in the project type field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > span > span.selection > span"
    And I enter in the project type value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)"
    And I enter in the date field with selector "#daterange"
    And I enter in the startdate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(1) > td:nth-child(7)"
    And I enter in the enddate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(6) > td:nth-child(2)"
    And I click on new phase "#agregarNuevaFase"
    And I enter in the phase name field with id "#fase1 > div.row.mt-4 > div:nth-child(1) > div > input" the text "Phase 1"
    And I enter in the phase hour field with id "#fase1 > div.row.mt-4 > div:nth-child(2) > div > input" the text "22"
    And I click on new phase "#agregarNuevaFase"
    And I enter in the phase name field with id "#fase2 > div.row.mt-4 > div:nth-child(1) > div > input" the text "Phase 2"
    And I enter in the phase hour field with id "#fase2 > div.row.mt-4 > div:nth-child(2) > div > input" the text "42"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/create"

  Scenario: Update a project with a new phase
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/show/1"
    And I click on the Nueva fase button on the new project with selector "body > div.wrapper > div > main > div > div > div.row > div:nth-child(3) > div > div > div.mb-3.d-flex.justify-content-between.align-items-center > a"
    And I enter in the phase name field with id "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.row > div:nth-child(1) > div > input" the text "Phase N"
    And I enter in the phase hour field with id "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.row > div:nth-child(2) > div > input" the text "66"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/create"

  Scenario: Update a project name
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/edit/1"
    And I enter in the project name field with name "nombre" the text "NewProjectName Test"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/create"

  Scenario: Update a project client
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/edit/1"
    And I enter in the client field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > span > span.selection > span > span.select2-selection__arrow"
    And I enter in the client-value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/show/1"

  Scenario: Update a project-manager
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/edit/1"
    And I enter in the project manager field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(2) > span"
    And I enter in the project manager value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(3)"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/show/1"

  Scenario: Update a project type
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/edit/1"
    And I enter in the project manager field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(5) > div:nth-child(1) > span"
    And I enter in the project manager value field with selector "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div:nth-child(5) > div:nth-child(1) > select > option:nth-child(3)"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/show/1"

  Scenario: Update a project date
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/edit/1"
    And I enter in the date field with selector "#daterange"
    And I click on the next month with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > thead > tr:nth-child(1) > th.next.available"
    And I click on the next month with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > thead > tr:nth-child(1) > th.next.available"
    And I enter in the startdate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(3) > td:nth-child(1)"
    And I enter in the enddate field with selector "body > div.daterangepicker.ltr.auto-apply.show-ranges.show-calendar.opensleft > div.drp-calendar.right > div.calendar-table > table > tbody > tr:nth-child(3) > td:nth-child(7)"
    And I click on save "body > div.wrapper > div > main > div > div > div.row > div > div > div > form > div.d-flex.justify-content-between > button"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/show/1"

  Scenario: Update a project status to the opposite status
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/"
    And I enter in the project status with selector "#navbarFixed"
    And I click on save "body > div.swal2-container.swal2-center.swal2-backdrop-show > div > div.swal2-actions > button.swal2-confirm.swal2-styled.swal2-default-outline"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/show/1"

  Scenario: Update a project status to the same status
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/"
    And I enter in the project status with selector "#navbarFixed"
    And I click on save "body > div.swal2-container.swal2-center.swal2-backdrop-show > div > div.swal2-actions > button.swal2-cancel.swal2-styled.swal2-default-outline"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/show/1"

  Scenario: Update a project deleting a phase
    Given I navigate to the url "https://taskhub.cl/"
    When I enter in the username field with id "email" the text "igna.veliz@duocuc.cl"
    And I enter in the password field with id "password" the text "123123123"
    And I click on the Login button with id "login_button"
    And I navigate to the url "https://taskhub.cl/proyecto/show/1"
    And I click on the delete fase button on the new project with selector "#FasesTable > tbody > tr.even > td:nth-child(6) > div > form > button"
    And I click on save "body > div.swal2-container.swal2-center.swal2-backdrop-show > div > div.swal2-actions > button.swal2-confirm.swal2-styled.swal2-default-outline"
    Then I should be redirected to the new project frame "https://taskhub.cl/proyecto/create"
